# Generated by Django 5.2.5 on 2025-09-04 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elevareApi', '0002_alter_user_password'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
